services:
  - type: worker
    name: vinted-discord-bot
    region: frankfurt
    plan: starter
    runtime: node
    buildCommand: "npm install"
    startCommand: "bash start.sh"
    envVars:
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: WATCH_URL
        sync: false